# fly.toml app configuration file generated for redis-example on 2023-05-11T22:28:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redis-example"
primary_region = "sea"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "redis_server"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics"
